---
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Copy the Zuul config file
  copy:
    src: "{{ ZUUL_CONF_PATH }}"
    dest: /etc/zuul/zuul.conf
    mode: 0644

- name: Create static folder for zuul-web
  file:
    path: "{{ ZUUL_USER_HOME }}/static"
    state: directory
    mode: 0770

- name: Copy app static files to Zuul home user static
  shell: cp -R /opt/zuul/zuul/web/static/* {{ ZUUL_USER_HOME }}/static

- name: Create static/js folder for zuul-web
  file:
    path: "{{ ZUUL_USER_HOME }}/static/js"
    state: directory
    mode: 0770

- name: Copy angular on static
  get_url:
    url: https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js
    dest: "{{ ZUUL_USER_HOME }}/static/js"
    owner: "{{ ZUUL_USER }}"
    group: root
    mode: 0644

- name: Copy jquery on static
  get_url:
    url: http://code.jquery.com/jquery.min.js
    dest: "{{ ZUUL_USER_HOME }}/static/js"
    owner: "{{ ZUUL_USER }}"
    group: root
    mode: 0644

- name: Copy jquery-visibility on static
  get_url:
    url: https://raw.githubusercontent.com/mathiasbynens/jquery-visibility/master/jquery-visibility.js
    dest: "{{ ZUUL_USER_HOME }}/static/js"
    owner: "{{ ZUUL_USER }}"
    group: root
    mode: 0644

- name: Copy jquery-graphite on static
  get_url:
    url: https://github.com/prestontimmons/graphitejs/blob/master/jquery.graphite.js
    dest: "{{ ZUUL_USER_HOME }}/static/js"
    owner: "{{ ZUUL_USER }}"
    group: root
    mode: 0644

- name: Copy twitter bootstrap on static
  unarchive:
    src: https://github.com/twbs/bootstrap/releases/download/v3.1.1/bootstrap-3.1.1-dist.zip
    dest: "{{ ZUUL_USER_HOME }}/static/"
    remote_src: yes
    owner: "{{ ZUUL_USER }}"
    group: root
    mode: 0770

- name: Rename bootstrap folder
  shell: mv {{ ZUUL_USER_HOME }}/static/bootstrap-3.1.1-dist {{ ZUUL_USER_HOME }}/static/bootstrap

- name: Link app static to Zuul home user static
  file:
    path: /opt/zuul/zuul/web/static
    state: absent

- name: Link app static to Zuul home user static
  file:
    src: "{{ ZUUL_USER_HOME }}/static"
    path: /opt/zuul/zuul/web/static
    state: link
    mode: 0770
