---
- name: Install Bigtop Centos 7 repo
  get_url:
    dest: /etc/yum.repos.d
    url: https://www.apache.org/dist/bigtop/stable/repos/centos7/bigtop.repo
    mode: 0644
    validate_certs: no

- name: Install epel, java and zookeeper
  yum: 
    name: "{{ item }}"
    state: present 
    disable_gpg_check: yes
  with_items:
    - epel-release
    - java
    - zookeeper

- name: Create Zookeeper user
  user:
    name: "{{ ZOOKEEPER_USER }}"
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "{{ ZOOKEEPER_USER_HOME }}"

- name: Chmod Zookeeper user home to 777 for OpenShift
  file:
    path: "{{ ZOOKEEPER_USER_HOME }}"
    state: directory
    mode: 0777
