---
- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    mode: 0775
    validate_certs: no

- name: Bootstrap rpm python bindings
  command: yum -y install rpm-python

- name: Install epel
  yum: 
    name: epel-release
    state: present 
    disable_gpg_check: yes

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python34-devel
    - python34-pip

- name: Install libcurl package
  yum:
    name: libcurl
    state: present
    update_cache: yes

- name: Update git package for getting curl https helper loaded
  yum:
    name: git
    state: latest

- name: Clone Zuul repo
  git:
    repo: 'git://github.com/openstack-infra/zuul'
    dest: /opt/zuul
    version: feature/zuulv3

- name: Install pip packages
  pip:
    executable: /usr/bin/pip3
    requirements: /opt/zuul/requirements.txt

- name: Install requirements
  pip:
    executable: /usr/bin/pip3
    name: typing

- name: Install Zuul from source
  pip:
    executable: /usr/bin/pip3
    name: /opt/zuul
    editable: yes

- name: Create Zuul user
  user:
    name: "{{ ZUUL_USER }}"
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "{{ ZUUL_USER_HOME }}"

- name: Create /etc/zuul folder
  file:
    path: /etc/zuul
    state: directory
    mode: 0755

- name: Clean yum cache
  command: yum clean all
