---
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl-devel
    - libffi-devel

- name: Clone Nodepool repo
  git:
    repo: 'git://github.com/openstack-infra/nodepool'
    dest: /opt/nodepool
    version: feature/zuulv3

- name: Update setuptools package with SCL Python 3.5
  command: scl enable rh-python35 "bash -c 'pip3 install -U setuptools'"

- name: Install pip packages with SCL Python 3.5
  command: scl enable rh-python35 "bash -c 'pip3 install -r /opt/nodepool/requirements.txt'"

- name: Install Nodepool from source with SCL Python 3.5
  command: scl enable rh-python35 "bash -c 'pip3 install -e /opt/nodepool'"

- name: Create Nodepool user
  user:
    name: "{{ NODEPOOL_USER }}"
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "{{ NODEPOOL_USER_HOME }}"

- name: Chmod Nodepool user home to 777 for OpenShift
  file:
    path: "{{ NODEPOOL_USER_HOME }}"
    state: directory
    mode: 0777

- name: Create the Nodepool user .ssh folder
  file:
    path: "{{ NODEPOOL_USER_HOME }}/.ssh"
    state: directory
    owner: "{{ NODEPOOL_USER }}"
    group: root
    mode: 0777

- name: Copy the Nodepool ssh key
  copy:
    src: "{{ NODEPOOL_KEY_PATH }}"
    dest: "{{ NODEPOOL_USER_HOME }}/.ssh/id_rsa"
    mode: 0644

- name: Create /etc/nodepool folder
  file:
    path: /etc/nodepool
    state: directory
    mode: 0755

- name: Create /etc/nodepool/secure.conf file
  file:
    path: /etc/nodepool/secure.conf
    state: touch
    mode: 0644

- name: Copy the Nodepool config file
  copy:
    src: "{{ NODEPOOL_YAML_PATH }}"
    dest: /etc/nodepool/nodepool.yaml
    mode: 0644

- name: Create /etc/openstack folder
  file:
    path: /etc/openstack
    state: directory
    mode: 0755

- name: Copy the Nodepool clouds file
  copy:
    src: "{{ NODEPOOL_CLOUDS_YAML_PATH }}"
    dest: /etc/openstack/clouds.yaml
    mode: 0644
