---
- name: Enable Software Collections repo
  yum:
    name: centos-release-scl
    state: present
    disable_gpg_check: yes

- name: Install SCL Python
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - rh-python35
